# Generated by Django 6.0.7 on 2026-08-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=150),
        ),
    ]
